import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser} from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.post.getAll.useQuery();
  const { isSignedIn } = useUser()

  console.log(data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!isSignedIn && <SignInButton mode="modal">
          <button className="btn">Sign in</button>
        </SignInButton>}

        {!!isSignedIn && <SignOutButton />}

        {data?.map(post => (<div key={post.id}>
          {post.content}
        </div>))}
      </main>
    </>
  );
};

export default Home;
